# Critical default settings:
#disable_system_gems
#disable_rubygems
#bundle_path ".gems/bundler_gems"

source :rubygems

# List gems to bundle here:
gem 'appengine-rack'
gem 'appengine-apis'
gem 'appengine-mapreduce'
gem 'json-jruby'

gem 'datamapper'
gem 'dm-appengine'

gem 'rspec'

gem 'sinatra'
gem 'haml'


gem 'jruby-openssl'
gem 'bundler'