# Critical default settings:
disable_system_gems
disable_rubygems
bundle_path ".gems/bundler_gems"

# List gems to bundle here:
gem 'appengine-rack'
gem 'appengine-apis'
gem 'appengine-mapreduce'
#gem 'json_pure'
gem 'json-jruby'

gem 'datamapper'
gem 'dm-appengine'

gem 'rspec'

gem 'sinatra'
