# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{appengine-mapreduce}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Nikitochkin"]
  s.date = %q{2010-09-18}
  s.description = %q{}
  s.email = %q{pftg@jetthoughts.com}
  s.files = [
    "Rakefile",
     "VERSION",
     "appengine-mapreduce-jruby.iml",
     "pom.xml",
     "src/LICENSE",
     "src/main/java/com/jetthoughts/appengine/tools/mapreduce/JRubyEvaluator.java",
     "src/main/java/com/jetthoughts/appengine/tools/mapreduce/JRubyMapper.java",
     "src/main/resources/appengine-mapreduce.rb",
     "src/main/resources/appengine-mapreduce/boot.rb",
     "src/main/resources/appengine-mapreduce/job.rb",
     "src/main/resources/com/jetthoughts/appengine/tools/mapreduce/ruby_wrapper.rb",
     "src/test/java/com/jetthoughts/appengine/tools/mapreduce/JRubyMapperTest.java"
  ]
  s.homepage = %q{http://github.com/pftg/appengine-mapreduce-jruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{AppEngine MapReduce JRuby Wrapper}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

