require 'rubygems'
require 'rake'

task :build do
  puts "Packaging jars with maven ..."
  system 'mvn package'
end


begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "appengine-mapreduce"
    gem.summary = %Q{ one-line summary of your gem}
    gem.description = %Q{ longer description of your gem}
    gem.email = "pftg@jetthoughts.com"
    gem.homepage = "http://github.com/defunkt/appengine-mapreduce"
    gem.authors = ["Paul Nikitochkin"]
    gem.add_development_dependency "thoughtbot-shoulda", ">= 0"
    gem.add_dependency "appengine-apis", ">= 0"

    gem.files =  Dir.glob('lib/**/*.rb')
    gem.files.include [
      "VERSION",
      "Rakefile",
      "target/**/*.jar"
    ]
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end


task :test => :check_dependencies

task :default => :test

