require 'rubygems'
require 'rake'


task :install_appengine_mapreduce do
  puts "Installing appengine-mapreduce artifact into maven"
  raise $? unless system 'cd ../appengine-mapreduce && mvn scm:bootstrap'
end

task :build do
  puts "Packaging jars with maven ..."
  raise $? unless system 'mvn package'
end


begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "appengine-mapreduce"
    gem.summary = %Q{AppEngine-MapReduce Wrappers and Tools for JRuby}
    gem.description = %Q{Create Map Tasks with JRuby.}
    gem.email = "pftg@jetthoughts.com"
    gem.homepage = "http://github.com/pftg/appengine-mapreduce"
    gem.authors = ["Paul Nikitochkin"]
    gem.add_dependency "appengine-apis", ">= 0"
    gem.platform = Gem::Platform::RUBY

    gem.files =  Dir.glob('lib/**/*.rb')
    gem.files.include [
      "VERSION",
      "COPYING",
      "NOTICE",
      "Rakefile",
      "target/**/*.jar"
    ]
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end


task :test => :check_dependencies

task :default => :test
